[#ftl output_format="HTML"]
        <!DOCTYPE html>
          <html lang="en">
          <head>
          
          
          
          <style>* { box-sizing: border-box; } body {margin: 0;}</style>
          
          </head>
          <body><meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Blank_Template</title></body>
          </html>